# -*- coding: utf-8 -*-
"""
/***************************************************************************
 imprimirAlvara
                                 A QGIS plugin
 Imprimir Alvará 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-07-09
        copyright            : (C) 2021 by Trindade Company
        email                : trindadeapp@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load imprimirAlvara class from file imprimirAlvara.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .imprimir_alvara import imprimirAlvara
    return imprimirAlvara(iface)
